import { checkBox } from "../models/checkBox";
import { SelectModel } from "../models/selectModel";

export class Default {

  public static OPCION_TYPES: Array<SelectModel> = [
    { value: 1, label: 'POSITIVO' },
    { value: 2, label: 'NEGATIVO' },

  ];
  public static chemicals: Array<checkBox> = [
    { id: 0, name: 'Indol(I)' },
    { id: 1, name: 'Rojo de Metilo(RM)' },
    { id: 2, name: 'Voges-Proskauer(VP)' },
    { id: 3, name: 'Citrato de Simmons' },
    { id: 4, name: 'Sulfuro de Hidrógeno(H2S)' },
    { id: 5, name: 'Urea(Urea)' },
    { id: 6, name: 'KCN' },
    { id: 7, name: 'Mobilidad(SIM)' },
    { id: 8, name: 'Gelatina(22C)' },
    { id: 9, name: 'Lisina Descarboxilasa(LIA)' },
    { id: 10, name: 'Arginia Dihidrolasa' },
    { id: 11, name: 'Ornitina Descarboxilasa' },
    { id: 12, name: 'Fenilalanina Desaminasa' },
    { id: 13, name: 'Malonato' },
    { id: 14, name: 'Gas de la Glucosa(K/A)' },
    { id: 15, name: 'Lactosa(K/K)' },
    { id: 16, name: 'Sacarosa(A/A)' },
    { id: 17, name: 'Manitol' },
    { id: 18, name: 'Dulcitol' },
    { id: 19, name: 'Salicina' },
    { id: 20, name: 'Adonitol' },
    { id: 21, name: 'Inositol' },
    { id: 22, name: 'Sorbitol' },
    { id: 23, name: 'Arabinosa' },
    { id: 24, name: 'Rafinosa' },
    { id: 25, name: 'Ramnosa' },
  ];
  public static mediums: Array<checkBox> = [
    { id: 0, name: 'Agar Acinetobacter' },
    { id: 1, name: 'Agar de Aislamiento de Actinomiceto' },
    { id: 2, name: 'Agar para Algas' },
    { id: 3, name: 'Medio Fluido para Anaerobios' },
    { id: 4, name: 'Agar APT (interpolación de uso múltiple)' },
    { id: 5, name: 'Agar B de King' },
    { id: 6, name: 'Agar Base al Purpura de Bromocresol' },
    { id: 7, name: 'Agar Sangre' },
    { id: 8, name: 'Agar Para Brucella' },
    { id: 9, name: 'Agar De Cistina Y Tripticasa' },
    { id: 10, name: 'Agar Citrato De Simmons' },
    { id: 11, name: 'Agar C.L.E.D (cistina-lactosa deficiente en electrolitos)' },
    { id: 12, name: 'Agar Selectivo De Clostridios' },
    { id: 13, name: 'Agar De Chapman Stone' },
    { id: 14, name: 'AGAR DE CHAPMAI\I TTC' },
    { id: 15, name: 'Agar Al Desoxicolato Con Citrato, Lactosa Y Sacarosa' },
    { id: 16, name: 'Agar Al Desoxicolato Y Citrato' },
    { id: 17, name: 'Agar Eutrofico' },
    { id: 18, name: 'Agar De Forget-Fredette ' },
    { id: 19, name: 'Agar MacConkey' },
    { id: 20, name: 'Agar Plate Count' },
    { id: 21, name: 'Agar M77' },
    { id: 22, name: 'Agar Manitol Salado' },
    { id: 23, name: 'Agar Sabouraud' },
    { id: 24, name: 'Caldo Peptona' },
    { id: 25, name: 'Caldo rojo de metilo (RM)' },
    { id: 26, name: 'Caldo Voges-Proskauer (VP)' },
    { id: 27, name: 'Caldo Malonato' },
    { id: 28, name: 'Agar Hierro-Triple Azúcar (TSI)' },
    { id: 29, name: 'Agar Lisina Hierro (LIA)' },
    { id: 30, name: 'Caldo Medio Mínimo De Sales De Davis (MMSD)' },
    { id: 31, name: 'Cetrimide' },
  ];

  public static bacterias: Array<any> = [
    {
      bacteria: 'ESCHERICHIEAE Escherichia A',
      pruebasObjeto: {
        "Indol(I)": 'POSITIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': 'NEGATIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': 'NEGATIVO',
        'KCN': 'NEGATIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'POSITIVO',
        'Arginia Dihidrolasa': 'POSITIVO',
        'Ornitina Descarboxilasa': 'POSITIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)(K/A)': 'POSITIVO',
        'Lactosa(K/K)': 'POSITIVO',
        'Sacarosa(A/A)': 'POSITIVO',
        'Manitol': 'POSITIVO',
        'Dulcitol': 'POSITIVO',
        'Salicina': 'POSITIVO',
        'Adonitol': 'NEGATIVO',
        'Inositol': 'NEGATIVO',
        'Sorbitol': 'POSITIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': 'POSITIVO',
        'Ramnosa': 'POSITIVO',
      },
    },
    {
      bacteria: 'ESCHERICHIEAE Escherichia B',
      pruebasObjeto: {
        "Indol(I)": 'POSITIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': 'NEGATIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': 'NEGATIVO',
        'KCN': 'NEGATIVO',
        'Mobilidad(SIM)': 'NEGATIVO',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'NEGATIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'NEGATIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)(K/A)': 'POSITIVO',
        'Lactosa(K/K)': 'POSITIVO',
        'Sacarosa(A/A)': 'NEGATIVO',
        'Manitol': 'POSITIVO',
        'Dulcitol': 'NEGATIVO',
        'Salicina': 'NEGATIVO',
        'Adonitol': 'NEGATIVO',
        'Inositol': 'NEGATIVO',
        'Sorbitol': 'NEGATIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': 'NEGATIVO',
      },
    },
    {
      bacteria: 'ESCHERICHIEAE Shigella A',
      pruebasObjeto: {
        "Indol(I)": 'POSITIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': 'NEGATIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': 'NEGATIVO',
        'KCN': 'NEGATIVO',
        'Mobilidad(SIM)': 'NEGATIVO',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'NEGATIVO',
        'Arginia Dihidrolasa': 'POSITIVO',
        'Ornitina Descarboxilasa': 'POSITIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)': 'POSITIVO',
        'Lactosa(K/K)': 'POSITIVO',
        'Sacarosa(A/A)': 'POSITIVO',
        'Manitol': 'POSITIVO',
        'Dulcitol': 'POSITIVO',
        'Salicina': 'NEGATIVO',
        'Adonitol': 'NEGATIVO',
        'Inositol': 'NEGATIVO',
        'Sorbitol': 'POSITIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': 'POSITIVO',
        'Ramnosa': 'POSITIVO',
      },
    },
    {
      bacteria: 'ESCHERICHIEAE Shigella B',
      pruebasObjeto: {
        "Indol(I)": 'NEGATIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': 'NEGATIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': 'NEGATIVO',
        'KCN': 'NEGATIVO',
        'Mobilidad(SIM)': 'NEGATIVO',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'NEGATIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'NEGATIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)': 'NEGATIVO',
        'Lactosa(K/K)': 'NEGATIVO',
        'Sacarosa(A/A)': 'NEGATIVO',
        'Manitol': 'NEGATIVO',
        'Dulcitol': 'NEGATIVO',
        'Salicina': 'NEGATIVO',
        'Adonitol': 'NEGATIVO',
        'Inositol': 'NEGATIVO',
        'Sorbitol': 'NEGATIVO',
        'Arabinosa': 'NEGATIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': 'NEGATIVO',
      },
    },
    {
      bacteria: 'EDWARDSIELLEAE Edwardsiella',
      pruebasObjeto: {
        "Indol(I)": 'POSITIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': 'NEGATIVO',
        'Sulfuro de Hidrógeno(H2S)': 'POSITIVO',
        'Urea(Urea)': 'NEGATIVO',
        'KCN': 'NEGATIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'POSITIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'POSITIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)': 'POSITIVO',
        'Lactosa(K/K)(K/K)': 'NEGATIVO',
        'Sacarosa(A/A)': 'NEGATIVO',
        'Manitol': 'NEGATIVO',
        'Dulcitol': 'NEGATIVO',
        'Salicina': 'NEGATIVO',
        'Adonitol': 'NEGATIVO',
        'Inositol': 'NEGATIVO',
        'Sorbitol': 'NEGATIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': 'NEGATIVO',
      },
    },
    {
      bacteria: 'SALMONELLEAE Salmonella A',
      pruebasObjeto: {
        "Indol(I)": 'NEGATIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': 'POSITIVO',
        'Sulfuro de Hidrógeno(H2S)': 'POSITIVO',
        'Urea(Urea)': 'NEGATIVO',
        'KCN': 'NEGATIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'POSITIVO',
        'Arginia Dihidrolasa': 'POSITIVO',
        'Ornitina Descarboxilasa': 'POSITIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)': 'POSITIVO',
        'Lactosa(K/K)': 'NEGATIVO',
        'Sacarosa(A/A)': 'NEGATIVO',
        'Manitol': 'POSITIVO',
        'Dulcitol': 'POSITIVO',
        'Salicina': 'NEGATIVO',
        'Adonitol': 'NEGATIVO',
        'Inositol': 'POSITIVO',
        'Sorbitol': 'POSITIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': 'POSITIVO',
      },
    },
    {
      bacteria: 'SALMONELLEAE Salmonella B',
      pruebasObjeto: {
        "Indol(I)": 'NEGATIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': 'NEGATIVO',
        'Sulfuro de Hidrógeno(H2S)': 'POSITIVO',
        'Urea(Urea)': 'NEGATIVO',
        'KCN': 'NEGATIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'POSITIVO',
        'Arginia Dihidrolasa': 'POSITIVO',
        'Ornitina Descarboxilasa': 'POSITIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)': 'POSITIVO',
        'Lactosa(K/K)': 'NEGATIVO',
        'Sacarosa(A/A)': 'NEGATIVO',
        'Manitol': 'POSITIVO',
        'Dulcitol': 'NEGATIVO',
        'Salicina': 'NEGATIVO',
        'Adonitol': 'NEGATIVO',
        'Inositol': 'NEGATIVO',
        'Sorbitol': 'POSITIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': 'POSITIVO',
      },
    },
    {
      bacteria: 'SALMONELLEAE Arizona',
      pruebasObjeto: {
        "Indol(I)": 'NEGATIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': 'POSITIVO',
        'Sulfuro de Hidrógeno(H2S)': 'POSITIVO',
        'Urea(Urea)': 'NEGATIVO',
        'KCN': 'NEGATIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'POSITIVO',
        'Lisina Descarboxilasa(LIA)': 'POSITIVO',
        'Arginia Dihidrolasa': 'POSITIVO',
        'Ornitina Descarboxilasa': 'POSITIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': 'POSITIVO',
        'Gas de la Glucosa(K/A)': 'POSITIVO',
        'Lactosa(K/K)': '(+ o -)',
        'Sacarosa(A/A)(A/A)': 'NEGATIVO',
        'Manitol': 'POSITIVO',
        'Dulcitol': 'NEGATIVO',
        'Salicina': 'NEGATIVO',
        'Adonitol': 'NEGATIVO',
        'Inositol': 'NEGATIVO',
        'Sorbitol': 'POSITIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': 'POSITIVO',
      },
    },
    {
      bacteria: 'SALMONELLEAE Citrobacter freundil',
      pruebasObjeto: {
        "Indol(I)": 'NEGATIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': 'POSITIVO',
        'Sulfuro de Hidrógeno(H2S)': '(+ o -)',
        'Urea(Urea)': '(+ o -)',
        'KCN': 'POSITIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'NEGATIVO',
        'Arginia Dihidrolasa': '(+ o -)',
        'Ornitina Descarboxilasa': '(+ o -)',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': '(+ o -)',
        'Gas de la Glucosa(K/A)': 'POSITIVO',
        'Lactosa(K/K)': '(+ o -)',
        'Sacarosa(A/A)': '(+ o -)',
        'Manitol': 'POSITIVO',
        'Dulcitol': '(+ o -)',
        'Salicina': '(+ o -)',
        'Adonitol': 'NEGATIVO',
        'Inositol': 'NEGATIVO',
        'Sorbitol': 'POSITIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': '(+ o -)',
        'Ramnosa': 'POSITIVO',
      },
    },
    {
      bacteria: 'SALMONELLEAE Citrobacter diversus',
      pruebasObjeto: {
        "Indol(I)": 'POSITIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': 'POSITIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': '(+ o -)',
        'KCN': 'NEGATIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'NEGATIVO',
        'Arginia Dihidrolasa': 'POSITIVO',
        'Ornitina Descarboxilasa': 'POSITIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': 'POSITIVO',
        'Gas de la Glucosa(K/A)': 'POSITIVO',
        'Lactosa(K/K)': '(+ o -)',
        'Sacarosa(A/A)': '(+ o -)',
        'Manitol': 'POSITIVO',
        'Dulcitol': '(+ o -)',
        'Salicina': 'POSITIVO',
        'Adonitol': 'POSITIVO',
        'Inositol': 'NEGATIVO',
        'Sorbitol': 'POSITIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': 'POSITIVO',
      },
    },
    {
      bacteria: 'KLEBSIELLAEA Klebsiella pneumoniae',
      pruebasObjeto: {
        "Indol(I)": 'NEGATIVO',
        'Rojo de Metilo(RM)': '(+ o -)',
        'Voges-Proskauer(VP)': 'POSITIVO',
        'Citrato de Simmons': 'POSITIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': 'POSITIVO',
        'KCN': 'POSITIVO',
        'Mobilidad(SIM)': 'NEGATIVO',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'POSITIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'NEGATIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': 'POSITIVO',
        'Gas de la Glucosa(K/A)': 'POSITIVO',
        'Lactosa(K/K)': 'POSITIVO',
        'Sacarosa(A/A)': 'POSITIVO',
        'Manitol': 'POSITIVO',
        'Dulcitol': '(+ o -)',
        'Salicina': 'POSITIVO',
        'Adonitol': '(+ o -)',
        'Inositol': 'POSITIVO',
        'Sorbitol': 'POSITIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': 'POSITIVO',
        'Ramnosa': 'POSITIVO',
      },
    },
    {
      bacteria: 'KLEBSIELLAEA Enterobacter cloreae',
      pruebasObjeto: {
        "Indol(I)": 'NEGATIVO',
        'Rojo de Metilo(RM)': 'NEGATIVO',
        'Voges-Proskauer(VP)': 'POSITIVO',
        'Citrato de Simmons': 'POSITIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': '(+ o -)',
        'KCN': 'POSITIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': '(+ o -)',
        'Lisina Descarboxilasa(LIA)': 'NEGATIVO',
        'Arginia Dihidrolasa': 'POSITIVO',
        'Ornitina Descarboxilasa': 'NEGATIVO',
        'Fenilalanina Desaminasa': '(+ o -)',
        'Malonato': '(+ o -)',
        'Gas de la Glucosa(K/A)': 'POSITIVO',
        'Lactosa(K/K)': 'POSITIVO',
        'Sacarosa(A/A)': 'POSITIVO',
        'Manitol': 'POSITIVO',
        'Dulcitol': '(+ o -)',
        'Salicina': 'POSITIVO',
        'Adonitol': '(+ o -)',
        'Inositol': 'POSITIVO',
        'Sorbitol': 'POSITIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': 'POSITIVO',
        'Ramnosa': 'POSITIVO',
      },
    },
    {
      bacteria: 'KLEBSIELLAEA Enterobacter aerogenes',
      pruebasObjeto: {
        "Indol(I)": 'NEGATIVO',
        'Rojo de Metilo(RM)': 'NEGATIVO',
        'Voges-Proskauer(VP)': 'POSITIVO',
        'Citrato de Simmons': 'POSITIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': 'NEGATIVO',
        'KCN': 'POSITIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': '(+ o -)',
        'Lisina Descarboxilasa(LIA)': 'POSITIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'POSITIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': '(+ o -)',
        'Gas de la Glucosa(K/A)': 'POSITIVO',
        'Lactosa(K/K)': 'POSITIVO',
        'Sacarosa(A/A)': 'POSITIVO',
        'Manitol': 'POSITIVO',
        'Dulcitol': 'NEGATIVO',
        'Salicina': 'POSITIVO',
        'Adonitol': 'POSITIVO',
        'Inositol': 'POSITIVO',
        'Sorbitol': 'POSITIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': 'POSITIVO',
        'Ramnosa': 'POSITIVO',
      },
    },
    {
      bacteria: 'KLEBSIELLAEA Enterobacter hafniae',
      pruebasObjeto: {
        "Indol(I)": 'NEGATIVO',
        'Rojo de Metilo(RM)': '(+ o -)',
        'Voges-Proskauer(VP)': '(+ o -)',
        'Citrato de Simmons': '(+ o -)',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': 'NEGATIVO',
        'KCN': 'POSITIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'POSITIVO',
        'Arginia Dihidrolasa': '(+ o -)',
        'Ornitina Descarboxilasa': 'POSITIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': '(+ o -)',
        'Gas de la Glucosa(K/A)': 'POSITIVO',
        'Lactosa(K/K)': '(+ o -)',
        'Sacarosa(A/A)': '(+ o -)',
        'Manitol': 'POSITIVO',
        'Dulcitol': 'NEGATIVO',
        'Salicina': '(+ o -)',
        'Adonitol': 'NEGATIVO',
        'Inositol': 'NEGATIVO',
        'Sorbitol': 'NEGATIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': 'POSITIVO',
      },
    },
    {
      bacteria: 'KLEBSIELLAEA Enterobacter agglomeruns',
      pruebasObjeto: {
        "Indol(I)": '(+ o -)',
        'Rojo de Metilo(RM)': '(+ o -)',
        'Voges-Proskauer(VP)': '(+ o -)',
        'Citrato de Simmons': '(+ o -)',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': '(+ o -)',
        'KCN': '(+ o -)',
        'Mobilidad(SIM)': '(+ o -)',
        'Gelatina(22C)': '(+ o -)',
        'Lisina Descarboxilasa(LIA)': 'NEGATIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'NEGATIVO',
        'Fenilalanina Desaminasa': '(+ o -)',
        'Malonato': '(+ o -)',
        'Gas de la Glucosa(K/A)': '(+ o -)',
        'Lactosa(K/K)': '(+ o -)',
        'Sacarosa(A/A)': '(+ o -)',
        'Manitol': 'POSITIVO',
        'Dulcitol': '(+ o -)',
        'Salicina': '(+ o -)',
        'Adonitol': 'NEGATIVO',
        'Inositol': '(+ o -)',
        'Sorbitol': '(+ o -)',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': '(+ o -)',
        'Ramnosa': '(+ o -)',
      },
    },
    {
      bacteria: 'KLEBSIELLAEA Serratia marcescens',
      pruebasObjeto: {
        "Indol(I)": 'NEGATIVO',
        'Rojo de Metilo(RM)': '(+ o -)',
        'Voges-Proskauer(VP)': 'POSITIVO',
        'Citrato de Simmons': 'POSITIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': '(+ o -)',
        'KCN': 'POSITIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'POSITIVO',
        'Lisina Descarboxilasa(LIA)': 'POSITIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'POSITIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)': '(+ o -)',
        'Lactosa(K/K)': 'NEGATIVO',
        'Sacarosa(A/A)': 'POSITIVO',
        'Manitol': 'POSITIVO',
        'Dulcitol': 'NEGATIVO',
        'Salicina': 'POSITIVO',
        'Adonitol': '(+ o -)',
        'Inositol': '(+ o -)',
        'Sorbitol': 'POSITIVO',
        'Arabinosa': 'NEGATIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': 'NEGATIVO',
      },
    },
    {
      bacteria: 'KLEBSIELLAEA Serratia liquefaciens',
      pruebasObjeto: {
        "Indol(I)": 'NEGATIVO',
        'Rojo de Metilo(RM)': '(+ o -)',
        'Voges-Proskauer(VP)': '(+ o -)',
        'Citrato de Simmons': 'POSITIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': '(+ o -)',
        'KCN': 'POSITIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'POSITIVO',
        'Lisina Descarboxilasa(LIA)': 'POSITIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'POSITIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)': '(+ o -)',
        'Lactosa(K/K)': '(+ o -)',
        'Sacarosa(A/A)': 'POSITIVO',
        'Manitol': 'POSITIVO',
        'Dulcitol': 'NEGATIVO',
        'Salicina': 'POSITIVO',
        'Adonitol': '(+ o -)',
        'Inositol': 'POSITIVO',
        'Sorbitol': 'POSITIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': 'POSITIVO',
        'Ramnosa': '(+ o -)',
      },
    },
    {
      bacteria: 'KLEBSIELLAEA Serratia rubidaea',
      pruebasObjeto: {
        "Indol(I)": 'NEGATIVO',
        'Rojo de Metilo(RM)': '(+ o -)',
        'Voges-Proskauer(VP)': 'POSITIVO',
        'Citrato de Simmons': 'POSITIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': '(+ o -)',
        'KCN': '(+ o -)',
        'Mobilidad(SIM)': '(+ o -)',
        'Gelatina(22C)': 'POSITIVO',
        'Lisina Descarboxilasa(LIA)': 'POSITIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'NEGATIVO',
        'Fenilalanina Desaminasa': 'NEGATIVO',
        'Malonato': '(+ o -)',
        'Gas de la Glucosa(K/A)': '(+ o -)',
        'Lactosa(K/K)': 'POSITIVO',
        'Sacarosa(A/A)': 'POSITIVO',
        'Manitol': 'POSITIVO',
        'Dulcitol': 'NEGATIVO',
        'Salicina': 'POSITIVO',
        'Adonitol': 'POSITIVO',
        'Inositol': '(+ o -)',
        'Sorbitol': 'NEGATIVO',
        'Arabinosa': 'POSITIVO',
        'Rafinosa': 'POSITIVO',
        'Ramnosa': 'NEGATIVO',
      },
    },
    {
      bacteria: 'PROTEEAE Proteus vulgaris',
      pruebasObjeto: {
        "Indol(I)": 'POSITIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': '(+ o -)',
        'Sulfuro de Hidrógeno(H2S)': 'POSITIVO',
        'Urea(Urea)': 'POSITIVO',
        'KCN': 'POSITIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'POSITIVO',
        'Lisina Descarboxilasa(LIA)': 'NEGATIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'NEGATIVO',
        'Fenilalanina Desaminasa': 'POSITIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)': '(+ o -)',
        'Lactosa(K/K)': 'NEGATIVO',
        'Sacarosa(A/A)': 'POSITIVO',
        'Manitol': 'NEGATIVO',
        'Dulcitol': 'NEGATIVO',
        'Salicina': '(+ o -)',
        'Adonitol': 'NEGATIVO',
        'Inositol': 'NEGATIVO',
        'Sorbitol': 'NEGATIVO',
        'Arabinosa': 'NEGATIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': 'NEGATIVO',
      },
    },
    {
      bacteria: 'PROTEEAE Proteus mirabilis',
      pruebasObjeto: {
        "Indol(I)": 'NEGATIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': '(+ o -)',
        'Citrato de Simmons': 'POSITIVO',
        'Sulfuro de Hidrógeno(H2S)': 'POSITIVO',
        'Urea(Urea)': 'POSITIVO',
        'KCN': 'POSITIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'POSITIVO',
        'Lisina Descarboxilasa(LIA)': 'NEGATIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'POSITIVO',
        'Fenilalanina Desaminasa': 'POSITIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)': 'POSITIVO',
        'Lactosa(K/K)': 'NEGATIVO',
        'Sacarosa(A/A)': '(+ o -)',
        'Manitol': 'NEGATIVO',
        'Dulcitol': 'NEGATIVO',
        'Salicina': '(+ o -)',
        'Adonitol': 'NEGATIVO',
        'Inositol': 'NEGATIVO',
        'Sorbitol': 'NEGATIVO',
        'Arabinosa': 'NEGATIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': 'NEGATIVO',
      },
    },
    {
      bacteria: 'PROTEEAE Proteus morgani',
      pruebasObjeto: {
        "Indol(I)": 'NEGATIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': 'NEGATIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': 'POSITIVO',
        'KCN': 'POSITIVO',
        'Mobilidad(SIM)': '(+ o -)',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'NEGATIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'POSITIVO',
        'Fenilalanina Desaminasa': 'POSITIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)': '(+ o -)',
        'Lactosa(K/K)': 'NEGATIVO',
        'Sacarosa(A/A)': 'NEGATIVO',
        'Manitol': 'NEGATIVO',
        'Dulcitol': 'NEGATIVO',
        'Salicina': 'NEGATIVO',
        'Adonitol': 'NEGATIVO',
        'Inositol': 'NEGATIVO',
        'Sorbitol': 'NEGATIVO',
        'Arabinosa': 'NEGATIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': 'NEGATIVO',
      },
    },
    {
      bacteria: 'PROTEEAE Proteus rettgeri',
      pruebasObjeto: {
        "Indol(I)": 'POSITIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': 'POSITIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': 'POSITIVO',
        'KCN': 'POSITIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'NEGATIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'NEGATIVO',
        'Fenilalanina Desaminasa': 'POSITIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)': '(+ o -)',
        'Lactosa(K/K)': 'NEGATIVO',
        'Sacarosa(A/A)': '(+ o -)',
        'Manitol': '(+ o -)',
        'Dulcitol': 'NEGATIVO',
        'Salicina': '(+ o -)',
        'Adonitol': '(+ o -)',
        'Inositol': 'POSITIVO',
        'Sorbitol': '(+ o -)',
        'Arabinosa': 'NEGATIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': '(+ o -)',
      },
    },
    {
      bacteria: 'PROTEEAE Providencia alcalifaciens',
      pruebasObjeto: {
        "Indol(I)": 'POSITIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': 'POSITIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': 'NEGATIVO',
        'KCN': 'POSITIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'NEGATIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'NEGATIVO',
        'Fenilalanina Desaminasa': 'POSITIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)': '(+ o -)',
        'Lactosa(K/K)': 'NEGATIVO',
        'Sacarosa(A/A)': '(+ o -)',
        'Manitol': 'NEGATIVO',
        'Dulcitol': 'NEGATIVO',
        'Salicina': 'NEGATIVO',
        'Adonitol': 'POSITIVO',
        'Inositol': 'NEGATIVO',
        'Sorbitol': 'NEGATIVO',
        'Arabinosa': 'NEGATIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': 'NEGATIVO',
      },
    },
    {
      bacteria: 'PROTEEAE Providencia stuartii',
      pruebasObjeto: {
        "Indol(I)": 'POSITIVO',
        'Rojo de Metilo(RM)': 'POSITIVO',
        'Voges-Proskauer(VP)': 'NEGATIVO',
        'Citrato de Simmons': 'POSITIVO',
        'Sulfuro de Hidrógeno(H2S)': 'NEGATIVO',
        'Urea(Urea)': 'NEGATIVO',
        'KCN': 'POSITIVO',
        'Mobilidad(SIM)': 'POSITIVO',
        'Gelatina(22C)': 'NEGATIVO',
        'Lisina Descarboxilasa(LIA)': 'NEGATIVO',
        'Arginia Dihidrolasa': 'NEGATIVO',
        'Ornitina Descarboxilasa': 'NEGATIVO',
        'Fenilalanina Desaminasa': 'POSITIVO',
        'Malonato': 'NEGATIVO',
        'Gas de la Glucosa(K/A)': 'NEGATIVO',
        'Lactosa(K/K)': 'NEGATIVO',
        'Sacarosa(A/A)': 'POSITIVO',
        'Manitol': '(+ o -)',
        'Dulcitol': 'NEGATIVO',
        'Salicina': 'NEGATIVO',
        'Adonitol': '(+ o -)',
        'Inositol': 'POSITIVO',
        'Sorbitol': '(+ o -)',
        'Arabinosa': 'NEGATIVO',
        'Rafinosa': 'NEGATIVO',
        'Ramnosa': 'NEGATIVO',
      },
    },
  ]

}


// TODO

